CREATE TABLE IF NOT EXISTS Categoria(
ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
Nombre TEXT(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Producto(
ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
Nombre TEXT(50) NOT NULL,
Marca TEXT(50) NOT NULL,
Precio_Und REAL(10),
Categoria_ID INTEGER,
FOREIGN KEY(Categoria_ID) REFERENCES Categoria(ID)  
);

CREATE TABLE IF NOT EXISTS Sucursales(
ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
Nombre TEXT(50) NOT NULL,
Direccion TEXT(50) NOT NULL 
);

CREATE TABLE IF NOT EXISTS Stock(
ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
Cantidad integer,
Producto_ID INTEGER,
Sucursal_ID INTEGER,
FOREIGN KEY(Producto_ID) REFERENCES Producto(ID),
FOREIGN KEY(Sucursal_ID) REFERENCES Sucursales(ID)
UNIQUE (Sucursal_ID, Producto_ID)
);

CREATE TABLE IF NOT EXISTS Cliente(
ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
Nombre TEXT(50) NOT NULL,
Telefono TEXT(20) NOT NULL 
);

CREATE TABLE IF NOT EXISTS Orden(
ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
Fecha DATETIME NOT NULL,
Total REAL(10) NOT NULL,
Cliente_ID INTEGER,
Sucursal_ID INTEGER,
FOREIGN KEY(Cliente_ID) REFERENCES Cliente(ID),
FOREIGN KEY(Sucursal_ID) REFERENCES Sucursales(ID)
);

CREATE TABLE IF NOT EXISTS Item(
ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
Cantidad INTEGER NOT NULL,
Monto_Venta REAL(10) NOT NULL,
Orden_ID INTEGER,
Producto_ID INTEGER,
FOREIGN KEY(Orden_ID) REFERENCES Orden(ID),
FOREIGN KEY(Producto_ID) REFERENCES Producto(ID)
);









